baseURL = "https://jmolina.cloud"
theme = "congo"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "jmolina.cloud"
enableEmoji = true
summaryLength = 0
enableRobotsTXT = true

[author]
  name = "Juanjo Molina"
  image = "img/profile.jpg"
  links = [
    { email = "mailto:juanjo@" },
    { github = "https://github.com/juanjo-mp" },
    { instagram = "https://www.instagram.com/juanjo_mp98/" },
  ]

[params]
  colorScheme = "avocado"
  env = "production"
  darkToggle = true

[params.homepage]
  layout = "profile"
  showRecent = false

[params.list]
  groupByYear = false
  showBreadcrumbs = false

[params.article]
  showDate = true
  showAuthor = false
  showReadingTime = true

[[menu.main]]
  name = "About"
  pageRef = "about"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Posts"
  pageRef = "posts"
  url = "/posts"
  weight = 20

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[taxonomies]
  topic = "topics"